server:
  port: 6015
  servlet:
    context-path: /heycheff

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:heycheffdb
    username: sa
    password: erp
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

media-base-path: "C:\\heycheff\\media"

cors:
  allowed-origins: "http://localhost:4200"
