media-server-paths: /home/heycheff/media

spring:
  cache:
    type: none

cors:
  allowed-origins: http://localhost:3000

heycheff:
  azure:
    account-name: acc-name
    account-key: acc-key
    blob-storage: blob
    container-name: blob-container
  oauth:
    google-client-id: gClientId
  clerk:
    secret: secretKey
  jwt:
    expiration: 600000
  jwk:
    jks-file: src/test/resources/heycheff.jks, src/test/resources/heycheff.jks
    password:
      key-store: test_storepass
      key-pass: test_keypass
    alias: heycheff
  redis:
    host: localhost
    port: 6379
    user: default
    password: default
    ssl: false
    ttl: 15
