server:
  port: 6015
  servlet:
    context-path: /heycheff

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: INFO

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 24MB

media-server-paths: C:\\heycheff\\media, /home/heycheff/media

cors:
  allowed-origins: http://179.124.193.12:3000, http://heycheff.com.br:3000, heycheff.com.br:3000

heycheff:
  jwt:
    expiration: 1800000
  jwk:
    jks-file: C:\\heycheff\\auth\\heycheff.jks, /home/heycheff/auth/heycheff.jks
    password:
      key-store: ${JKS_STORE_PASS}
      key-pass: ${JKS_KEY_PASS}
    alias: heycheff
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    user: ${REDIS_USER}
    password: ${REDIS_PASSWORD}
    ssl: true
    ttl: 15
