server:
  port: 6015
  servlet:
    context-path: /heycheff

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/heycheff
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:heycheffdb
#    username: sa
#    password: erp
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 24MB

media-server-paths: C:\\heycheff\\media, /bin/heycheff/media

cors:
  allowed-origins: http://localhost:4200, http://localhost:3000
