server:
  port: 6015
  servlet:
    context-path: /heycheff

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:heycheffdb
    username: sa
    password: erp
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
