INSERT INTO UNIDADEMEDIDA(descricao) VALUES('grama');
INSERT INTO TAG(tag) values('Salgado');
INSERT INTO TAG(tag) values('Doce');
INSERT INTO TAG(tag) values('Vegano');
INSERT INTO TAG(tag) values('Vegetariano');
INSERT INTO TAG(tag) values('Fast Food');
INSERT INTO TAG(tag) values('Massa');
INSERT INTO TAG(tag) values('Italiana');
INSERT INTO TAG(tag) values('Brasileira');
INSERT INTO TAG(tag) values('Nordestina');
INSERT INTO TAG(tag) values('Japonesa');
INSERT INTO TAG(tag) values('Mexicana');
INSERT INTO TAG(tag) values('Chinesa');
INSERT INTO TAG(tag) values('Indiana');
INSERT INTO TAG(tag) values('Tailandesa');
INSERT INTO TAG(tag) values('Grega');
INSERT INTO TAG(tag) values('Árabe');
